apiVersion: v1
kind: ConfigMap
metadata:
  name: klyra-state
  namespace: {{ include "klyra.namespace" . }}
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
data:
  state.json: "{}"
