apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "klyra.name" . }}-config
  namespace: {{ include "klyra.namespace" . }}
data:
  config.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
